language: node_js
dist: trusty
node_js:
  - 7
  - 8
cache:
  directories:
  - node_modules
sudo: false
git:
  depth: 3
install:
- yarn
script:
- yarn test

after_success: yarn coverage

cache:
  yarn: true
  directories:
  - node_modules
