language: node_js
dist: trusty
node_js:
  - 7
  - 8
cache:
  directories:
  - node_modules
sudo: false
git:
  depth: 3
install:
- npm install
script:
- npm run test:ci

after_success: npm run coverage

cache:
  directories:
  - node_modules
